- hosts: all
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
    - name: "Install standard packages"
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - rsync
        - screen
        - strace
        - vim
        - git
        - sudo
        - ansible
    - name: "Remove nano"
      apt:
        name: nano
        state: removed
    - include: docker.yml


